### PR TITLE
Accumulated Enhancements

### PR DESCRIPTION
**Pull request by Wackerbarth**
This includes the changes from PR#81. The main thrust of those changes is to bring in a more recent base OS (Ubuntu 18.04) and BBB support (2018-12-10)

The Redeem and Toggle daemons each now have their own virtual environment.
There is also provided a mechanism to allow a developer to select from multiple versions of those programs without having to wipe out the other copies.

The standard practice of denying direct "root" login has been restored. The user now logs in as "ubuntu" and uses "sudo" to gain root access.

mdns access is provided to assist access to other local computers.

Some minor adjustments are made to the interface templates to improve the quality of the OP response.

### CODE REVIEW

**Comment by goeland86** [comment]
> The standard practice of denying direct "root" login has been restored. The user now logs in as "ubuntu" and uses "sudo" to gain root access.

No. No. No. No.

The reason Ubuntu & Debian remove `root` from the SSH access list is to protect the machine/device when it's publicly exposed to the web.

A 3D printer should **never** be out in the open this way. Gina has tried to make that super clear with OctoPrint, adding "nagging" popups, at-length blog posts etc.

There is no justification for removing the root account for a machine running on a local network.
Worse, the official documentation specifically outlines the use of root : kamikaze as the SSH login.

I thought the MDNS PR was already merged into the Umikaze base? If not, merge that PR instead.

The practice of creating **one PR to rule them all** obfuscates what is being done, and makes it harder to revert individual features later. It also makes it difficult to track in the intelligent-agent organization the features that were merged. Your personal repo is for feature development - this repository is here to integrate them. Do not push integrated changes from your fork - it breaks the whole concept of the organization repository that we have.

**Comment by Wackerbarth** [comment]
Jon, the practice of not being "root" all of the time has more to do with protecting the OS from inadvertent mistakes of the user.
Unless absolutely necessary, you should never operate as root.  OctoPrint does it properly by running as the "octo" user and using "sudo" to execute those commands which require root access.

We should really be doing the same.

**Comment by goeland86** [comment]
No - I disagree in this case. For one thing the installation of Redeem is always run as root - whether in a venv or not.

Further, we have a significant number of users who, for good or bad, follow wiki instructions about how to switch branches without knowing anything about permissions. The documentation always referred to running as root to avoid permissions problems that users will run into.

Hiding these manipulations behind sudo does not make the system any safer. It may make more sense on a desktop or server environment where you want to protect basic system files, but on a printer controller where the re-install of the system is a matter of 20 minutes with the SD card, it loses all purpose.

All you're doing is adding an extra layer of complexity for users to deal with, and forcing them to learn Linux permissions when they really shouldn't have to when they RTFM. The ones who risk breaking the system are beyond the base level and will break their systems with or without the root account.

**Comment by Wackerbarth** [comment]
The reason all of Redeem runs as "root" is because no one has bothered to set proper permissions on the individual components. For example, a common activity is to examine log files. You do not need all of the power of root to do that. And, if permissions are set properly, you would not need to use sudo either.

Doing everything as root is just the lazy way out.

**Comment by goeland86** [comment]
No, that's incorrect. When you run `journalctl` or `systemctl` you need either sudo or root access to view those logs. Granted you could also create a group etc. But again. You're not protecting anything, just adding extra steps in the setup of the machine.

**Comment by Wackerbarth** [comment]
Those groups already exist. And you ARE protecting things by restricting the user. For example, as a journalctl user, you cannot erase or overwrite a running daemon.

And "setup" is something that we do once, in the build scripts.

**Comment by goeland86** [comment]
> And "setup" is something that we do once, in the build scripts.

Or everytime a user changes a branch.
Again, you're ignoring the fact that users who want to break things, will. Whether you make them use sudo or not. This change brings nothing but pain to the users out there, and there's no gains to be had.

I will not approve this PR anyway, due to the more salient point you haven't addressed about the combination of features in a single PR.

**Comment by Wackerbarth** [comment]
I don't know why you say that "changes a branch" causes a permissions issue. Once the administrative user gets set up with proper permissions, they are there. Changing a branch doesn't change permissions.

As to the issue of "one big PR", the problem is that the initial PR81 was incomplete and could/should not be merged at that time. While those issues were being sorted out, other changes were also being developed. We've finally gotten to a point where we again have a working build. I don't propose squashing them all together. But if you want to go in and sort things into separate PRs, you will need to make corrections to PR81 because, as is, it is not exactly correct. I find no value in preserving the PR itself. Rather it is the individual commits that should be viewed as the fundamental unit. I think that this PR presents the accumulated changes in a manner that can be understood and it leads to a tested conclusion. By adjusting the final selection of versions for the major components, it can build a reasonable ReleaseCandidate for our present system.

**Comment by Wackerbarth** [comment]
By the way -- If you really want to be "root" every time you log in, we can supply a profile patch to automatically `sudo bash` as you log in.

**Comment by ThatWileyGuy** [comment]
We had the sudo vs root debate a long time ago and it basically came down to two points:
- exposing a 3d printer to the open internet is a catastrophic mistake even without root access, so denying root SSH doesn't help anything from a network security perspective
- the BBBs that run our images are single-use machines where there's basically everything a user will ever want to do over SSH will be a privileged operation, so trying to maintain the normal "use sudo for important stuff" model doesn't really serve anyone's needs

On a normal Linux workstation, most of the tasks a user will do will not require privileged access to the system. In this environment, it makes sense to train users to avoid root and use sudo only when necessary. Our environment, however, exists for the sole purpose of running a 3d printer and "privileged operations" are those that affect how the printer operates. There are no other tasks a normal user will run on their BBB, so it makes little sense to try and use an "unprivileged session" - this will just create the habit of running everything under sudo.

These considerations lead us to decide that we might as well go straight for root logon for convenience because there's basically no security benefit from doing otherwise.

**Comment by Wackerbarth** [comment]
Well, with decades of experience administering Unix systems, and building dedicated systems similar to our printer, I really disagree. There are VERY few different things that anyone should be doing on the printer. And most of those are either of the "look around" or "activate a canned procedure" variety. The former should not be any issue for someone who has "administrator" permissions. The latter should be done by suid scripts that we have provided to do those functions. As a result, there should be VERY little need for anyone to become "root". The danger in being "root" is that the least typo can have devastating effect. And you will not hear about it very often because the culprit will not complain about a problem that they know to be caused by their own fault. They just go to the effort to restore the system and chalk it up to their mistake.

So, I repeat that the benefit is not "security" in the sense of keeping someone from doing something. But it does make sure that the individual either does things following the "policy" that we establish or they explicitly acknowledge that they are not following policy.

**Comment by goeland86** [comment]
Well I'm sorry Richard, but no. I'm also a Linux sysadmin, and I agree with
Andrew on this.

Our printer does not need extra policy fluff to confuse people who are
coming from the Arduino world.

You're not looking at who the user base is, and projecting your personal
preference on a community of people who are generally independent minded
and smart. If they decide to learn looking and setup their printers with
security policies etc on top of it, great. But I do not want to lose people
because we forced a change in their behavior for no good reason.

As Andrew said, we've had the discussion and debate several times before
you joined the project, with other sysadmins in the lot, and decided to
forgo the sudo rule for a reason.

Do not presume to impose a change on the community whose sole purpose is to
force people to your way of doing things.

If you do not agree with what's been decided, your welcome to create your
line of images (wackermaze for example) and we'll happily let you implement
those changes you want to have in that image.

In the meantime, Andrew and I will continue to build Umikaze as per the
expected community standards and will consider and pull request you make
that enhances the image within those standards. We expect you to do the
same while contributing to the intelligent-agent repository.

**Comment by Wackerbarth** [comment]
Sorry, but I think that I AM considering the user base.  They need everything to be super-simple. And there is a very limited list of things that they need to do. Each of those should be reduced to a very simple command (with the details hidden in a suid script). The less sophisticated the user, the more they need to be kept away from being "root".

**Comment by goeland86** [comment]
Again, no. You're willfully misunderstanding what I said. Read again the
paragraph about expected community standards.

That standard was devasted at length before your arrival, and nothing you
say is something that hasn't been said before. And ultimately we still
decided to go with root.

Let it go.

**Pull request closed without merging**
