### PR TITLE
Make Redeem installation selectable

### PR DESCRIPTION
**Pull request by Wackerbarth**
This change accomplishes two things:
First, it causes Redeem to be installed in its own virtual environment.
These virtual environments are placed in /usr/local/ to avoid conflicts with the base operating system.
Where the intent is to work with multiple versions, /usr/local/ can be expanded by mounting an auxillary volume on that mountpoint. Instead, a "normal" user can have a single instance on the root volume.

Second, it provides a configuration file selectable choice from multiple versions of Redeem.
This provides the developer/tester an easy method to swap versions without having to do a reinstall.

A future enhancement will be the management of the selection configuration file by the OP-Redeem UI wizard.

### CODE REVIEW

**Comment by goeland86** [comment]
@Wackerbarth I don't understand how this is different from what the "virtualize_redeem" call was previously doing, though admittedly I didn't compare what you're changing against `virtualize_redeem`. I understand the concepts at play but not the implementations that were done.

**Comment by Wackerbarth** [comment]
This replaces "virtualize_redeem" and merges it with "install_redeem" (per @ThatWileyGuy's request). It also adds the mechanism which performs the selection at `systemctl start` time. "virtualize_redeem" was a hack that allowed the scheme to work by modifying a non-virtual installation. This change does the virtualenv creation and install in a clean manner.

**Comment by ThatWileyGuy** [comment]
This generally looks reasonable, but I'm wondering why you wanted the Select_A_Service machinery. 

Out-of-the-box, the python venv/egg machinery lets you have multiple Redeem installs in multiple virtual envs, and the last one you ran `setup.py develop` in will always launch when you run `/usr/local/bin/redeem` because running `setup.py develop` updates the path in `/usr/local/lib/python2.7/dist-packages/Redeem.egg-link`.

What makes you prefer writing a config file over that?

**Comment by Wackerbarth** [comment]
The selection mechanism is there to provide a way to switch between established installations without having to rebuild them each time. My use case is to have, for example, a "production" configuration, a development configuration and some temporary configuration that I need to test. It is quite possible that some of those configurations might not include the source installation but be installed from eggs.

**Comment by Wackerbarth** [comment]
I have rebased and adjusted the commits to reflect other PRs that were merged ahead of this one.
It required some time to sort things out and produce the desired merge. Since this whole build ecosystem is still settling out, changes often impact files that are being modified by multiple developers.

I suggest that we adopt a "lock" protocol to sequence these changes.

I suggest that #86 be merged first. Then we pass the lock to #81.
After that, we can look to see what else is pending and establish some order.

Although the actual base upon which a PR starts is unknown, having advance knowledge of the likely content will simplify adjusting to that starting base when the time comes to merge the PR.

And, hopefully, the system will settle down and changes will become less frequent and more likely to affect only localized portions of the system.

**Comment by ThatWileyGuy** [comment]
> The selection mechanism is there to provide a way to switch between established installations without having to rebuild them each time. My use case is to have, for example, a "production" configuration, a development configuration and some temporary configuration that I need to test. It is quite possible that some of those configurations might not include the source installation but be installed from eggs.
> 
> Ultimately, each configuration will have its own version of the configuration files, etc. and we will need a mechanism to link the components (Redeem, Toggle, OP, etc.) to the currently active component.
> 
> Although the mechanism is somewhat complex, it is really just a mechanism to make life easier for developers and testers. I anticipate that the "normal" user will have only one instance of each component and have no need to alter the selections. However, from the systems view, that can be considered a special case which is included in the more general solution.
> 
> I envision that we will add a "configuration wizard" that will be able to manage the Select_A_Service configuration file

What bothers me is that everything you've described can be achieved by editing `/usr/local/lib/python2.7/dist-packages/Redeem.egg-link` directly. It's just a path. It carries the same information you want to put into Select_A_Service.conf, but with the added benefit python can edit it for you in the developer common case that you just want to run the most recent Redeem you built. And if you don't want that, you just use `setup.py build` instead of `setup.py develop` and you can edit the same file on your own.

**Comment by Wackerbarth** [comment]
I don't think that it does carry the same information. (1) We have multiple venv domains and they need to have cross domain links. For example, the OP plugins that alter the Redeem setup need to access the individual instance configuration files. And there is no requirement that a particular component be in python2.7. In fact, one of the reasons for using multiple venv's is to be able to have some parts of the system in python2.7 while others get updated to python3. Having a standardized configuration file for this inter-domain connectivity will make it easy to have those plugins find the proper directories that they need to manipulate. (2) If there are additional executables, the scheme that you suggest would require that all of them be rebuilt whenever the meta-environment is changed.

By maintaining parallel environments and selecting the one that needs to be active at any given time, those problems are avoided. Once an environment is set up, by any means, it can be selected without the requirement that rebuilding it be an automated process.

**Comment by Wackerbarth** [comment]
As for "python can edit it for you", setup.py can also be configured to edit the Select_A_Service.conf also.

**Comment by Wackerbarth** [comment]
I'm NOT adding any service. This simply controls which version of a particular service gets activated.

IMHO, as a developer, this makes it much easier to make multiple use of the hardware for testing various versions, doing production printing, or whatever I wish to use the printer for.

**Comment by goeland86** [comment]
I think we're losing focus on the main goal of Umikaze: providing a user-friendly ready to run BBB image for Replicape/Revolve.

We should create a separate repository with an overlay for all the developer enhancements you want to have. They don't belong in a "production" image, which is what we're trying to provide...

**Comment by Wackerbarth** [comment]
@goeland86 - I don't agree that having a "hook" present hurts the "production" system. I don't expect many users to ever have more than one version loaded UNLESS they are a developer OR they agree to help us test something.

For that last group of users, requiring a minimal change on their part is a big plus for us because they won't have to "rebuild" things just to do the testing.

**Comment by ThatWileyGuy** [comment]
In general, this change bothers me both because it seems to be a problem we can already solve without the extra abstractions and because reducing the 99% use case to a special case feels a bit silly. I suspect that this feature will see very little use, but it's possible that I'm wrong.

There's also nothing obviously technically wrong or logically unsound about it, though, so I'm willing to sign off. We'll have to see how it goes.

**Comment by Wackerbarth** [comment]
@ThatWileyGuy - Thanks. I hope that it will get used to assist us in having users doing testing.

**Pull request merged**
