### PR TITLE
Updated suffix and decompress algorithm on base image

### PR DESCRIPTION
**Pull request by eliasbakken**
Buster current has xz compression, not 7z

### CODE REVIEW

**Comment by goeland86** [comment]
Automated build failed. Please check that the PR builds, and if it changes the parameters needed for the build, explain how so a Jenkins admin can validate the build.

**Comment by eliasbakken** [comment]
How do I see the build status? Is there a link here?

**Comment by goeland86** [comment]
Uh, that was an automated message.

The build log should be visible if you click on the little red x next to the commit

**Comment by goeland86** [comment]
... Ok please be patient with me while I fix Jenkins. It did not build for this PR, and it shouldn't have placed that comment.

**Pull request closed without merging**
